### ISSUE TITLE
Add CSS Animations

### ISSUE THREAD

**Issue by Leo-Oberndorfer** [Leo-Oberndorfer/DeveloperIsland#7]
Some nice animations and transitions on the homepage would be pretty nice.
Also add some to the course sites when they are done.

**Comment by Leo-Oberndorfer** [comment]
I tried working on it for a bit but maybe @Lejla-Music should take care of it as I'm not really good when it comes to design and animations

**Comment by Lejla-Music** [comment]
working on it

**Comment by Leo-Oberndorfer** [comment]
Added; More animations may follow in the future
